#pragma once

// GENERATED by lang/gen_help.py -- do not edit by hand.
// Edit help.<lang>.txt in this folder and re-run the generator.
//
// Included from the bottom of HelpLang.h, so HelpLang must not
// include this file back.

#include <pgmspace.h>
#include <stdint.h>

enum HelpId : uint16_t {
  H_INDEX_TITLE = 0,
  H_INDEX_LANG = 1,
  H_SNIFFERS_TITLE = 2,
  H_SNIFFERS_BEACON_NAME = 3,
  H_SNIFFERS_BEACON_WHAT = 4,
  H_SNIFFERS_BEACON_WHEN = 5,
  H_SNIFFERS_EAPOL_NAME = 6,
  H_SNIFFERS_EAPOL_WHAT = 7,
  H_SNIFFERS_EAPOL_WHEN = 8,
  H_SNIFFERS_PROBE_NAME = 9,
  H_SNIFFERS_PROBE_WHAT = 10,
  H_SNIFFERS_PROBE_WHEN = 11,
  H_SNIFFERS_DEAUTH_NAME = 12,
  H_SNIFFERS_DEAUTH_WHAT = 13,
  H_SNIFFERS_DEAUTH_WHEN = 14,
  H_SNIFFERS_PKT_NAME = 15,
  H_SNIFFERS_PKT_WHAT = 16,
  H_SNIFFERS_PKT_WHEN = 17,
  H_SNIFFERS_CHAN_NAME = 18,
  H_SNIFFERS_CHAN_WHAT = 19,
  H_SNIFFERS_CHAN_WHEN = 20,
  H_SNIFFERS_RAW_NAME = 21,
  H_SNIFFERS_RAW_WHAT = 22,
  H_SNIFFERS_RAW_WHEN = 23,
  H_SNIFFERS_SAE_NAME = 24,
  H_SNIFFERS_SAE_WHAT = 25,
  H_SNIFFERS_SAE_WHEN = 26,
  H_SNIFFERS_PINE_NAME = 27,
  H_SNIFFERS_PINE_WHAT = 28,
  H_SNIFFERS_PINE_WHEN = 29,
  H_ATTACKS_TITLE = 30,
  H_ATTACKS_DEAUTH_NAME = 31,
  H_ATTACKS_DEAUTH_WHAT = 32,
  H_ATTACKS_DEAUTH_WHEN = 33,
  H_ATTACKS_TARGETED_NAME = 34,
  H_ATTACKS_TARGETED_WHAT = 35,
  H_ATTACKS_TARGETED_WHEN = 36,
  H_ATTACKS_PROBE_NAME = 37,
  H_ATTACKS_PROBE_WHAT = 38,
  H_ATTACKS_PROBE_WHEN = 39,
  H_ATTACKS_BEACON_NAME = 40,
  H_ATTACKS_BEACON_WHAT = 41,
  H_ATTACKS_BEACON_WHEN = 42,
  H_ATTACKS_CSA_NAME = 43,
  H_ATTACKS_CSA_WHAT = 44,
  H_ATTACKS_CSA_WHEN = 45,
  H_ATTACKS_SAE_NAME = 46,
  H_ATTACKS_SAE_WHAT = 47,
  H_ATTACKS_SAE_WHEN = 48,
  H_ATTACKS_QUIET_NAME = 49,
  H_ATTACKS_QUIET_WHAT = 50,
  H_ATTACKS_QUIET_WHEN = 51,
  H_SCANNERS_TITLE = 52,
  H_SCANNERS_PING_NAME = 53,
  H_SCANNERS_PING_WHAT = 54,
  H_SCANNERS_PING_WHEN = 55,
  H_SCANNERS_ARP_NAME = 56,
  H_SCANNERS_ARP_WHAT = 57,
  H_SCANNERS_ARP_WHEN = 58,
  H_SCANNERS_TELNET_NAME = 59,
  H_SCANNERS_TELNET_WHAT = 60,
  H_SCANNERS_TELNET_WHEN = 61,
  H_SCANNERS_SSH_NAME = 62,
  H_SCANNERS_SSH_WHAT = 63,
  H_SCANNERS_SSH_WHEN = 64,
  H_SCANNERS_HTTP_NAME = 65,
  H_SCANNERS_HTTP_WHAT = 66,
  H_SCANNERS_HTTP_WHEN = 67,
  H_SCANNERS_RDP_NAME = 68,
  H_SCANNERS_RDP_WHAT = 69,
  H_SCANNERS_RDP_WHEN = 70,
  H_CAPTURE_TITLE = 71,
  H_CAPTURE_STEP1_A = 72,
  H_CAPTURE_STEP1_A_2 = 73,
  H_CAPTURE_STEP2_A = 74,
  H_CAPTURE_STEP3_A = 75,
  H_CAPTURE_STEP4_A = 76,
  H_CAPTURE_STEP5_A = 77,
  H_CAPTURE_STEP6_A = 78,
  H_CAPTURE_STEP7_A = 79,
  H_CAPTURE_STEP8_A = 80,
  H_TERMS_TITLE = 81,
  H_TERMS_EAPOL_A = 82,
  H_TERMS_EAPOL_A_2 = 83,
  H_TERMS_SAE_A = 84,
  H_TERMS_SAE_A_2 = 85,
  H_TERMS_PMKID_A = 86,
  H_TERMS_BSSID_A = 87,
  H_TERMS_SSID_A = 88,
  H_TERMS_PROMISCUOUS_A = 89,
  H_TERMS_PROMISCUOUS_A_2 = 90,
  H_TERMS_DEAUTH_A = 91,
  H_TERMS_DEAUTH_A_2 = 92,
  H_TERMS_PCAPNG_A = 93,
  H_TERMS_PCAP_A = 94,
  H_TERMS_PCAP_A_2 = 95,
  HELP_ID_MAX = 96
};

namespace help_gen {

// One flat blob of NUL-separated strings. Offsets are uint16 rather
// than const char* so each index cell costs 2 bytes instead of 4 and
// the table needs no relocations.
inline const char kPool[] PROGMEM =
  "Quick Reference\0"
  "Language\0"
  "WiFi > Sniffers\0"
  "Beacon Sniff\0"
  "Lists nearby APs, keeps one beacon\0"
  "Use first, to find a BSSID\0"
  "EAPOL/PMKID Scan\0"
  "Saves 4-way keys, sends deauth too\0"
  "Use for a known AP\0"
  "Probe Request Sniff\0"
  "What devices are looking for\0"
  "Use to see networks sought\0"
  "Deauth Sniff\0"
  "Who is kicked, and by whom\0"
  "Use to spot a jammer\0"
  "Packet Monitor\0"
  "Counts packets per channel\0"
  "Use to find a quiet channel\0"
  "Channel Analyzer\0"
  "Live traffic graph, one channel\0"
  "Use to watch a channel\0"
  "Raw Capture\0"
  "Every frame, nothing filtered\0"
  "Use when unsure what to seek\0"
  "SAE Commit\0"
  "The WPA3 handshake equivalent\0"
  "Use when the target is WPA3\0"
  "Detect Pineapple\0"
  "Finds rogue APs cloning a real one\0"
  "Use to audit your own venue\0"
  "WiFi > Attacks\0"
  "Deauth Flood\0"
  "Kicks every client off the AP\0"
  "Use to force a reconnection\0"
  "Deauth Targeted\0"
  "Kicks one chosen client only\0"
  "Use to drop a single device\0"
  "Probe Req Flood\0"
  "Advertises many fake networks\0"
  "Use to test client list building\0"
  "Beacon Spam List\0"
  "Replays beacons taken from a file\0"
  "Use to test beacon parsing\0"
  "Channel Switch\0"
  "Forces clients to another channel\0"
  "Use to see if a client follows\0"
  "SAE Commit Flood\0"
  "Drives WPA3 authentication tries\0"
  "Use to study SAE exchanges\0"
  "Quiet Time\0"
  "Sends nothing, only observes\0"
  "Use for passive checks\0"
  "WiFi > Scanners\0"
  "Ping Scan\0"
  "Shows which addresses answer\0"
  "Use to find live hosts\0"
  "ARP Scan\0"
  "Maps IP to hardware address\0"
  "Use to build an inventory\0"
  "Telnet Scan\0"
  "Finds port 23 open and reachable\0"
  "Use to find un-managed gear\0"
  "SSH Scan\0"
  "The same, on port 22\0"
  "Use to spot exposed servers\0"
  "HTTP / HTTPS\0"
  "Web servers and their titles\0"
  "Use to identify a device\0"
  "RDP Scan\0"
  "Remote desktop hosts, port 3389\0"
  "Use to check open desktops\0"
  "Capture a handshake\0"
  "1. Beacon Sniff, note the BSSID you\0"
  "want.\0"
  "2. EAPOL/PMKID Scan, tap your own AP.\0"
  "3. Deauth goes out, the client\0"
  "4. The 4-way handshake runs.\0"
  "5. Complete EAPOL counts the finished\0"
  "6. The capture file lands on the SD\0"
  "7. Every frame names the AP it came\0"
  "8. Red Dropped means the buffer was\0"
  "Terms\0"
  "EAPOL: the 4-way key handshake,\0"
  "802.1X.\0"
  "SAE: Simultaneous Auth. of Equals,\0"
  "WPA3.\0"
  "PMKID: Pairwise Master Key Identifier.\0"
  "BSSID: the hardware address of an AP.\0"
  "SSID: the name of a network.\0"
  "Promiscuous: hears all traffic, not\0"
  "just ours.\0"
  "Deauth: a frame that forces a rejoin.\0"
  "\0"
  "pcapng: capture file that keeps notes.\0"
  "pcap: older format, read by\0"
  "aircrack-ng.\0"
  "Hizli Basvuru\0"
  "Dil\0"
  "WiFi > Koklayicilar\0"
  "Beacon Tarama\0"
  "AP'leri listeler, beacon saklar\0"
  "Once hedef BSSID'i bulmak icin\0"
  "EAPOL/PMKID Tara\0"
  "4 yonlu anahtari kaydeder\0"
  "Bilinen bir AP icin kullanilir\0"
  "Probe Istek Tarama\0"
  "Cihazlar ne ag ariyor\0"
  "Aranan aglari gormek icin\0"
  "Deauth Tarama\0"
  "Kim atiliyor, kim atiyor\0"
  "Bozucu bir AP fark etmek icin\0"
  "Paket Izleme\0"
  "Kanal basina paket sayar\0"
  "En sessiz kanal bulmak icin\0"
  "Kanal Analizi\0"
  "Tek kanal icin canli grafik\0"
  "Bir kanali izlemek icin\0"
  "Ham Kayit\0"
  "Her cerceve, filtresiz\0"
  "Neyin aranacagi belli degilken\0"
  "WPA3 el sikisma karsiligi\0"
  "Hedef ag WPA3 ise\0"
  "Pineapple Bul\0"
  "Sahte AP'leri bulur\0"
  "Kendi mekanini denetlemek icin\0"
  "WiFi > Saldirilar\0"
  "Deauth Seli\0"
  "Butun istemcileri atar\0"
  "Yeniden baglanmayi zorlamak icin\0"
  "Hedefli Deauth\0"
  "Yalnizca tek istemciyi atar\0"
  "Tek cihazi dusurmek icin\0"
  "Probe Istek Seli\0"
  "Cok sayida sahte ag ilan eder\0"
  "Istemci liste davranisini olcmek\0"
  "Beacon Spam\0"
  "Dosyadan beacon tekrarlar\0"
  "Beacon ayristirmasini test etmek\0"
  "Kanal Degistirme\0"
  "Baska kanala zorlar\0"
  "Istemci AP'yi izliyor mu\0"
  "SAE Commit Seli\0"
  "WPA3 dogrulamasini baslatir\0"
  "SAE akisini incelemek icin\0"
  "Sessiz Mod\0"
  "Hicbir sey gondermez\0"
  "Yan etkisiz pasif calisma icin\0"
  "WiFi > Tarayicilar\0"
  "Ping Tarama\0"
  "Hangi adresler cevap veriyor\0"
  "Canli cihazlari bulmak icin\0"
  "ARP Tarama\0"
  "IP'yi donanim adresine baglar\0"
  "Envanter cikarmak icin\0"
  "Telnet Tarama\0"
  "23. portun acik oldugunu bulur\0"
  "Yabanci cihaz bulmak icin\0"
  "SSH Tarama\0"
  "Aynisi, 22. portta\0"
  "Acik sunuculari fark etmek\0"
  "Web sunucularini ve basligini\0"
  "Cihazin ne oldugunu anlamak\0"
  "RDP Tarama\0"
  "Uzak masaustu, 3389 portu\0"
  "Acik masaustleri denetlemek\0"
  "El sikisma yakalama\0"
  "1. Beacon Tarama, istedigin BSSID'i\0"
  "not al.\0"
  "2. EAPOL/PMKID Tara, kendi AP'ni sec.\0"
  "3. Deauth gider, istemci geri gelir.\0"
  "4. Dort yonlu el sikisma olusur.\0"
  "5. Complete EAPOL bitenleri sayar.\0"
  "6. Kayit dosyasi SD kartta belirir.\0"
  "7. Her cerceve AP'sini yazar.\0"
  "8. Kirmizi Dropped tampon dolu demek.\0"
  "Terimler\0"
  "EAPOL: 802.1X'in dort yonlu el\0"
  "sikismasi.\0"
  "SAE: Esitlerin Eszamanli Dogrulamasi,\0"
  "PMKID: Eslesme Anahtari Kimligi.\0"
  "BSSID: bir AP'nin donanim adresi.\0"
  "SSID: bir agin adi.\0"
  "Promiscuous: yalnizca kendi degil, tum\0"
  "trafik.\0"
  "Deauth: yeniden baglamaya zorlayan\0"
  "cerceve.\0"
  "pcapng: not tutan kayit dosyasi.\0"
  "pcap: aircrack-ng'in okudugu eski\0"
  "bicim.\0"
  ;

inline const uint16_t kOffsets[LANG_COUNT][96] PROGMEM = {
  [LANG_EN] = {
    0, 16, 25, 41, 54, 89, 116, 133, 168, 187, 207, 236, 263, 276, 303, 324, 339, 366, 394, 411, 443, 466, 478, 508, 537, 548, 578, 606, 623, 658, 686, 701, 714, 744, 772, 788, 817, 845, 861, 891, 924, 941, 975, 1002, 1017, 1051, 1082, 1099, 1132, 1159, 1170, 1199, 1222, 1238, 1248, 1277, 1300, 1309, 1337, 1363, 1375, 1408, 1436, 1445, 1466, 1494, 1507, 1536, 1561, 1570, 1602, 1629, 1649, 1685, 1691, 1729, 1760, 1789, 1827, 1863, 1899, 1935, 1941, 1973, 1981, 2016, 2022, 2061, 2099, 2128, 2164, 2175, 2213, 2214, 2253, 2281
  },
  [LANG_TR] = {
    2294, 2308, 2312, 2332, 2346, 2378, 2409, 2426, 2452, 2483, 2502, 2524, 2550, 2564, 2589, 2619, 2632, 2657, 2685, 2699, 2727, 2751, 2761, 2784, 537, 2815, 2841, 2859, 2873, 2893, 2924, 2942, 2954, 2977, 3010, 3025, 3053, 3078, 3095, 3125, 3158, 3170, 3196, 3229, 3246, 3266, 3291, 3307, 3335, 3362, 3373, 3394, 3425, 3444, 3456, 3485, 3513, 3524, 3554, 3577, 3591, 3622, 3648, 3659, 3678, 1494, 3705, 3735, 3763, 3774, 3800, 3828, 3848, 3884, 3892, 3930, 3967, 4000, 4035, 4071, 4101, 4139, 4148, 4179, 4190, 2016, 4228, 4261, 4295, 4315, 4354, 4362, 4397, 4406, 4439, 4473
  },
};

}  // namespace help_gen

inline const char *helpText(HelpId id) {
  if (id >= HELP_ID_MAX) return "";
  return &help_gen::kPool[pgm_read_word(
      &help_gen::kOffsets[helpGetLang()][id])];
}

// Collects the wrapped lines of one field, starting at `base`.
// Continuation ids are allocated contiguously, so this walks
// forward and stops at the first empty one.
inline uint8_t helpLines(HelpId base, const char **out, uint8_t max) {
  uint8_t n = 0;
  for (uint16_t i = base; i < HELP_ID_MAX && n < max; ++i, ++n) {
    const char *s = helpText(static_cast<HelpId>(i));
    if (s == nullptr || s[0] == '\0') break;
    out[n] = s;
  }
  return n;
}
